### ISSUE TITLE
Sidebar won't scroll

### ISSUE THREAD

**Issue by chongchonghe** [sbsrnt/physics-calc-v2#8]
Both on the website: https://physics-calc.netlify.app/ and the local host via yarn, the sidebar menu won't scroll. 
See the image attached:

<img width="1148" alt="Screen Shot 2020-07-25 at 10 53 43 AM" src="https://user-images.githubusercontent.com/24463821/88459707-62090b00-ce65-11ea-8757-3a21b0ffc98f.png">

**Comment by sbsrnt** [comment]
Aye, sorry for the late reply. Didn't really pay attention to that project (´。＿。｀). In fact there is no overflow safety net* implemented. Was planning to fix the dependencies anyway so will do that soon.

**Comment by sbsrnt** [comment]
Released in [#1.1.1](https://github.com/sbsrnt/physics-calc-v2/blob/master/CHANGELOG.md#111-2020-08-12)
